<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Brands Export</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.4;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h1 {
            margin: 0;
            font-size: 18px;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f5f5f5;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Brands Report</h1>
        <p>Generated on {{ now()->format('M d, Y H:i:s') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>No</th>
                <th>Name</th>
                <th>Description</th>
                <th>Vehicles</th>
                <th>Created At</th>
            </tr>
        </thead>
        <tbody>
            @foreach($brands as $i => $brand)
                <tr>
                    <td>{{ $i + 1 }}</td>
                    <td>{{ $brand->name }}</td>
                    <td>{{ $brand->description ?? '-' }}</td>
                    <td>{{ $brand->vehicles_count }}</td>
                    <td>{{ $brand->created_at->format('M d, Y H:i') }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Report generated by {{ config('app.name') }} - {{ now()->format('Y') }}</p>
    </div>
</body>
</html>
