<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Vehicles Export</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 10px;
            line-height: 1.3;
        }
        .header {
            text-align: center;
            margin-bottom: 15px;
        }
        .header h1 {
            margin: 0;
            font-size: 16px;
        }
        .header p {
            margin: 3px 0;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 4px;
            text-align: left;
        }
        th {
            background-color: #f5f5f5;
            font-weight: bold;
            font-size: 9px;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            margin-top: 20px;
            text-align: center;
            font-size: 8px;
            color: #666;
        }
        .no-wrap {
            white-space: nowrap;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Vehicles Report</h1>
        <p>Generated on {{ now()->format('M d, Y H:i:s') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>No</th>
                <th>Police Number</th>
                <th>Brand</th>
                <th>Type</th>
                <th>Model</th>
                <th>Year</th>
                <th>Chassis No</th>
                <th>Engine No</th>
                <th>Cylinder</th>
                <th>Kilometer</th>
                <th>Warehouse</th>
                <th>Registration Date</th>
                <th>Registration Expiry</th>
                <th>Purchase Date</th>
                <th>Purchase Price</th>
                <th>Selling Date</th>
                <th>Selling Price</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($vehicles as $i => $vehicle)
                <tr>
                    <td>{{ $i + 1 }}</td>
                    <td class="no-wrap">{{ $vehicle->police_number }}</td>
                    <td>{{ $vehicle->brand?->name ?? '-' }}</td>
                    <td>{{ $vehicle->type?->name ?? '-' }}</td>
                    <td>{{ $vehicle->vehicle_model?->name ?? '-' }}</td>
                    <td>{{ $vehicle->year }}</td>
                    <td class="no-wrap">{{ $vehicle->chassis_number }}</td>
                    <td class="no-wrap">{{ $vehicle->engine_number }}</td>
                    <td>{{ $vehicle->cylinder_capacity ? number_format($vehicle->cylinder_capacity, 0) . 'cc' : '-' }}</td>
                    <td class="no-wrap">{{ number_format($vehicle->kilometer, 0) }}</td>
                    <td>{{ $vehicle->warehouse?->name ?? '-' }}</td>
                    <td>{{ $vehicle->vehicle_registration_date ? \Carbon\Carbon::parse($vehicle->vehicle_registration_date)->format('M d, Y') : '-' }}</td>
                    <td>{{ $vehicle->vehicle_registration_expiry_date ? \Carbon\Carbon::parse($vehicle->vehicle_registration_expiry_date)->format('M d, Y') : '-' }}</td>
                    <td>{{ $vehicle->purchase_date ? \Carbon\Carbon::parse($vehicle->purchase_date)->format('M d, Y') : '-' }}</td>
                    <td class="no-wrap">{{ $vehicle->purchase_price ? 'Rp ' . number_format($vehicle->purchase_price, 0) : '-' }}</td>
                    <td>{{ $vehicle->selling_date ? \Carbon\Carbon::parse($vehicle->selling_date)->format('M d, Y') : '-' }}</td>
                    <td class="no-wrap">{{ $vehicle->selling_price ? 'Rp ' . number_format($vehicle->selling_price, 0) : '-' }}</td>
                    <td>{{ $vehicle->status == 1 ? 'Available' : 'Sold' }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Report generated by {{ config('app.name') }} - {{ now()->format('Y') }}</p>
    </div>
</body>
</html>

