<div>
    <div class="relative mb-6 w-full">
        <flux:heading size="xl" level="1">
            Detail Sinyal Saham
            @if($isAutoGenerated)
                <flux:badge color="blue" size="sm" class="ml-3">
                    <svg class="size-3 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17h14a2 2 0 002-2V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"></path>
                    </svg>
                    Auto-generated
                </flux:badge>
            @endif
        </flux:heading>
        <flux:subheading size="lg" class="mb-6">{{ $signal->kode_emiten }} - {{ $signal->stockCompany->nama_emiten ?? '' }}</flux:subheading>
        <flux:separator variant="subtle" />
    </div>

    <!-- Actions Bar -->
    <div class="flex items-center justify-between gap-4 mb-3 mt-5">
        <div class="flex items-center gap-2">
            <flux:button variant="primary" size="sm" href="{{ route('admin.signals.edit', $signal) }}" wire:navigate icon="pencil-square">
                Edit Sinyal
            </flux:button>
            <flux:button variant="ghost" size="sm" href="{{ route('admin.signals.index') }}" wire:navigate icon="arrow-left">
                Kembali
            </flux:button>
        </div>
    </div>

    <!-- Alert Messages -->
    @session('success')
        <x-alert type="success" class="mb-4">{{ $value }}</x-alert>
    @endsession

    @session('error')
        <x-alert type="error" class="mb-4">{{ $value }}</x-alert>
    @endsession

    <div class="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <!-- Main Content -->
        <div class="lg:col-span-2 space-y-6">
            <!-- Signal Overview -->
            <div class="bg-white dark:bg-zinc-800 rounded-lg border border-gray-200 dark:border-zinc-700 overflow-hidden">
                <div class="px-6 py-4 border-b border-gray-200 dark:border-zinc-700 bg-gray-50 dark:bg-zinc-800/50">
                    <div class="flex items-center justify-between">
                        <h3 class="text-lg font-semibold text-gray-900 dark:text-white">Ringkasan Sinyal</h3>
                        <flux:badge color="{{ $signal->status === 'published' ? 'green' : ($signal->status === 'active' ? 'blue' : 'gray') }}" size="sm">
                            {{ $signal->status_label }}
                        </flux:badge>
                    </div>
                </div>
                <div class="p-6">
                    <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                        <div class="space-y-4">
                            <div class="flex justify-between items-center py-2 border-b border-gray-100 dark:border-zinc-700">
                                <span class="text-sm font-medium text-gray-500 dark:text-zinc-400">Kode Emiten:</span>
                                <span class="text-sm font-semibold text-gray-900 dark:text-white">{{ $signal->kode_emiten }}</span>
                            </div>

                            <div class="flex justify-between items-center py-2 border-b border-gray-100 dark:border-zinc-700">
                                <span class="text-sm font-medium text-gray-500 dark:text-zinc-400">Tipe Sinyal:</span>
                                <div class="flex items-center gap-2">
                                    <flux:badge color="blue" size="sm">
                                        {{ ucfirst(str_replace('_', ' ', $signal->signal_type)) }}
                                    </flux:badge>
                                    @if($isAutoGenerated)
                                        <svg class="size-4 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17h14a2 2 0 002-2V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"></path>
                                        </svg>
                                    @endif
                                </div>
                            </div>

                            <div class="flex justify-between items-center py-2 border-b border-gray-100 dark:border-zinc-700">
                                <span class="text-sm font-medium text-gray-500 dark:text-zinc-400">Market Cap:</span>
                                <span class="text-sm text-gray-900 dark:text-white">{{ $signal->formatted_market_cap }}</span>
                            </div>

                            <div class="flex justify-between items-center py-2 border-b border-gray-100 dark:border-zinc-700">
                                <span class="text-sm font-medium text-gray-500 dark:text-zinc-400">PBV:</span>
                                <span class="text-sm text-gray-900 dark:text-white">{{ $signal->formatted_pbv }}</span>
                            </div>

                            <div class="flex justify-between items-center py-2">
                                <span class="text-sm font-medium text-gray-500 dark:text-zinc-400">PER:</span>
                                <span class="text-sm text-gray-900 dark:text-white">{{ $signal->formatted_per }}</span>
                            </div>
                        </div>

                        <div class="space-y-4">
                            <div class="flex justify-between items-center py-2 border-b border-gray-100 dark:border-zinc-700">
                                <span class="text-sm font-medium text-gray-500 dark:text-zinc-400">Tanggal Hit:</span>
                                <span class="text-sm text-gray-900 dark:text-white">{{ $signal->hit_date ? $signal->hit_date->format('d/m/Y') : '-' }}</span>
                            </div>

                            <div class="flex justify-between items-center py-2 border-b border-gray-100 dark:border-zinc-700">
                                <span class="text-sm font-medium text-gray-500 dark:text-zinc-400">Dibuat:</span>
                                <span class="text-sm text-gray-900 dark:text-white">{{ $signal->created_at->format('d/m/Y H:i') }}</span>
                            </div>

                            <div class="flex justify-between items-center py-2 border-b border-gray-100 dark:border-zinc-700">
                                <span class="text-sm font-medium text-gray-500 dark:text-zinc-400">Diubah:</span>
                                <span class="text-sm text-gray-900 dark:text-white">{{ $signal->updated_at->format('d/m/Y H:i') }}</span>
                            </div>

                            @if($signal->published_at)
                                <div class="flex justify-between items-center py-2 border-b border-gray-100 dark:border-zinc-700">
                                    <span class="text-sm font-medium text-gray-500 dark:text-zinc-400">Dipublikasikan:</span>
                                    <span class="text-sm text-gray-900 dark:text-white">{{ $signal->published_at->format('d/m/Y H:i') }}</span>
                                </div>
                            @endif

                            <div class="flex justify-between items-center py-2">
                                <span class="text-sm font-medium text-gray-500 dark:text-zinc-400">Oleh:</span>
                                <span class="text-sm text-gray-900 dark:text-white">
                                    @if($signal->user)
                                        {{ $signal->user->name }}
                                    @else
                                        <span class="text-gray-500 dark:text-zinc-400">Sistem</span>
                                    @endif
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Technical Data -->
            <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
                <!-- H-1 Data -->
                <div class="bg-blue-50 dark:bg-blue-950/20 rounded-lg border border-blue-200 dark:border-blue-800 overflow-hidden">
                    <div class="px-4 py-3 border-b border-blue-200 dark:border-blue-800 bg-blue-100 dark:bg-blue-900/30">
                        <div class="flex items-center gap-2">
                            <flux:icon.arrow-left class="size-4 text-blue-600 dark:text-blue-400" />
                            <h4 class="text-sm font-semibold text-blue-900 dark:text-blue-100">Data H-1 (Sebelum)</h4>
                        </div>
                    </div>
                    <div class="p-4 space-y-3">
                        <div class="flex justify-between items-center">
                            <span class="text-sm text-blue-700 dark:text-blue-300">Tanggal:</span>
                            <span class="text-sm font-medium text-blue-900 dark:text-blue-100">{{ $signal->before_date ? $signal->before_date->format('d/m/Y') : '-' }}</span>
                        </div>
                        <div class="flex justify-between items-center">
                            <span class="text-sm text-blue-700 dark:text-blue-300">Nilai:</span>
                            <span class="text-sm font-medium text-blue-900 dark:text-blue-100">{{ $signal->before_value ? 'Rp ' . number_format($signal->before_value, 0, ',', '.') : '-' }}</span>
                        </div>
                        <div class="flex justify-between items-center">
                            <span class="text-sm text-blue-700 dark:text-blue-300">Harga Close:</span>
                            <span class="text-sm font-medium text-blue-900 dark:text-blue-100">{{ $signal->before_close ? 'Rp ' . number_format($signal->before_close, 0, ',', '.') : '-' }}</span>
                        </div>
                        <div class="flex justify-between items-center">
                            <span class="text-sm text-blue-700 dark:text-blue-300">Volume:</span>
                            <span class="text-sm font-medium text-blue-900 dark:text-blue-100">{{ $signal->before_volume ? number_format($signal->before_volume, 0, ',', '.') : '-' }}</span>
                        </div>
                    </div>
                </div>

                <!-- H Data -->
                <div class="bg-purple-50 dark:bg-purple-950/20 rounded-lg border border-purple-200 dark:border-purple-800 overflow-hidden">
                    <div class="px-4 py-3 border-b border-purple-200 dark:border-purple-800 bg-purple-100 dark:bg-purple-900/30">
                        <div class="flex items-center gap-2">
                            <flux:icon.bolt class="size-4 text-purple-600 dark:text-purple-400" />
                            <h4 class="text-sm font-semibold text-purple-900 dark:text-purple-100">Data H (Breakthrough)</h4>
                        </div>
                    </div>
                    <div class="p-4 space-y-3">
                        <div class="flex justify-between items-center">
                            <span class="text-sm text-purple-700 dark:text-purple-300">Tanggal:</span>
                            <span class="text-sm font-bold text-purple-900 dark:text-purple-100">{{ $signal->hit_date ? $signal->hit_date->format('d/m/Y') : '-' }}</span>
                        </div>
                        <div class="flex justify-between items-center">
                            <span class="text-sm text-purple-700 dark:text-purple-300">Nilai:</span>
                            <span class="text-sm font-bold text-purple-900 dark:text-purple-100">{{ $signal->hit_value ? 'Rp ' . number_format($signal->hit_value, 0, ',', '.') : '-' }}</span>
                        </div>
                        <div class="flex justify-between items-center">
                            <span class="text-sm text-purple-700 dark:text-purple-300">Harga Close:</span>
                            <span class="text-sm font-bold text-purple-900 dark:text-purple-100">{{ $signal->hit_close ? 'Rp ' . number_format($signal->hit_close, 0, ',', '.') : '-' }}</span>
                        </div>
                        <div class="flex justify-between items-center">
                            <span class="text-sm text-purple-700 dark:text-purple-300">Volume:</span>
                            <span class="text-sm font-bold text-purple-900 dark:text-purple-100">{{ $signal->hit_volume ? number_format($signal->hit_volume, 0, ',', '.') : '-' }}</span>
                        </div>
                    </div>
                </div>

                <!-- H+1 Data -->
                <div class="bg-green-50 dark:bg-green-950/20 rounded-lg border border-green-200 dark:border-green-800 overflow-hidden">
                    <div class="px-4 py-3 border-b border-green-200 dark:border-green-800 bg-green-100 dark:bg-green-900/30">
                        <div class="flex items-center gap-2">
                            <flux:icon.arrow-right class="size-4 text-green-600 dark:text-green-400" />
                            <h4 class="text-sm font-semibold text-green-900 dark:text-green-100">Data H+1 (Sesudah)</h4>
                        </div>
                    </div>
                    <div class="p-4 space-y-3">
                        <div class="flex justify-between items-center">
                            <span class="text-sm text-green-700 dark:text-green-300">Tanggal:</span>
                            <span class="text-sm font-medium text-green-900 dark:text-green-100">{{ $signal->after_date ? $signal->after_date->format('d/m/Y') : '-' }}</span>
                        </div>
                        <div class="flex justify-between items-center">
                            <span class="text-sm text-green-700 dark:text-green-300">Nilai:</span>
                            <span class="text-sm font-medium text-green-900 dark:text-green-100">{{ $signal->after_value ? 'Rp ' . number_format($signal->after_value, 0, ',', '.') : '-' }}</span>
                        </div>
                        <div class="flex justify-between items-center">
                            <span class="text-sm text-green-700 dark:text-green-300">Harga Close:</span>
                            <span class="text-sm font-medium text-green-900 dark:text-green-100">{{ $signal->after_close ? 'Rp ' . number_format($signal->after_close, 0, ',', '.') : '-' }}</span>
                        </div>
                        <div class="flex justify-between items-center">
                            <span class="text-sm text-green-700 dark:text-green-300">Volume:</span>
                            <span class="text-sm font-medium text-green-900 dark:text-green-100">{{ $signal->after_volume ? number_format($signal->after_volume, 0, ',', '.') : '-' }}</span>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Recommendation -->
            <div class="bg-white dark:bg-zinc-800 rounded-lg border border-gray-200 dark:border-zinc-700 overflow-hidden">
                <div class="px-6 py-4 border-b border-gray-200 dark:border-zinc-700 bg-gray-50 dark:bg-zinc-800/50">
                    <h3 class="text-lg font-semibold text-gray-900 dark:text-white">Rekomendasi Investasi</h3>
                </div>
                <div class="p-6">
                    <p class="text-gray-700 dark:text-gray-300 leading-relaxed">{{ $signal->recommendation }}</p>
                </div>
            </div>

            <!-- Notes -->
            @if($signal->notes)
                <div class="bg-white dark:bg-zinc-800 rounded-lg border border-gray-200 dark:border-zinc-700 overflow-hidden">
                    <div class="px-6 py-4 border-b border-gray-200 dark:border-zinc-700 bg-gray-50 dark:bg-zinc-800/50">
                        <h3 class="text-lg font-semibold text-gray-900 dark:text-white">Catatan Tambahan</h3>
                    </div>
                    <div class="p-6">
                        <p class="text-gray-700 dark:text-gray-300 leading-relaxed">{{ $signal->notes }}</p>
                    </div>
                </div>
            @endif
        </div>

        <!-- Sidebar -->
        <div class="lg:col-span-1 space-y-6">
            <!-- Stock Price -->
            @if($stockPriceData)
                <div class="bg-white dark:bg-zinc-800 rounded-lg border border-gray-200 dark:border-zinc-700 overflow-hidden">
                    <div class="px-6 py-4 border-b border-gray-200 dark:border-zinc-700 bg-gray-50 dark:bg-zinc-800/50">
                        <h3 class="text-lg font-semibold text-gray-900 dark:text-white">Harga Saham Terakhir</h3>
                    </div>
                    <div class="p-6">
                        <div class="space-y-4">
                            <!-- Company Info -->
                            <div class="flex items-center">
                                <div
                                    class="relative w-12 h-12 shrink-0"
                                    x-data="{ imageLoaded: false, imageError: false }"
                                    x-init="imageLoaded = false; imageError = false"
                                    wire:key="stock-logo-{{ $signal->kode_emiten }}"
                                >
                                    {{-- Fallback initials --}}
                                    <div
                                        class="absolute inset-0 rounded-full bg-gray-200 dark:bg-zinc-700 flex items-center justify-center"
                                        x-show="!imageLoaded || imageError"
                                        x-cloak
                                    >
                                        <span class="text-gray-600 dark:text-zinc-400 font-bold text-xs">{{ substr($signal->kode_emiten, 0, 2) }}</span>
                                    </div>
                                    {{-- Logo image --}}
                                    @if($signal->stockCompany && $signal->stockCompany->logo_url)
                                        <img
                                            src="{{ $signal->stockCompany->logo_url }}"
                                            alt="{{ $signal->kode_emiten }}"
                                            class="absolute inset-0 w-12 h-12 rounded-full object-contain bg-white dark:bg-zinc-800 p-0.5"
                                            x-show="imageLoaded && !imageError"
                                            x-cloak
                                            x-on:load="imageLoaded = true"
                                            x-on:error="imageError = true"
                                        />
                                    @endif
                                </div>
                                <div class="flex flex-col ml-3">
                                    <a href="#" wire:click="selectStock('{{ $signal->kode_emiten }}')" class="hover:no-underline">{{ $signal->kode_emiten }}</a>
                                    @if($signal->stockCompany)
                                        <div class="text-sm text-gray-500 dark:text-zinc-400">
                                            {{ $signal->stockCompany->nama_emiten ?? '' }}
                                        </div>
                                    @endif
                                </div>
                            </div>

                            <!-- Price Data -->
                            <div class="grid grid-cols-2 gap-4">
                                <div class="bg-blue-50 dark:bg-blue-950/20 border border-blue-200 dark:border-blue-800 rounded-lg p-3">
                                    <p class="text-xs text-blue-600 dark:text-blue-400 uppercase tracking-wider font-medium">Close</p>
                                    <p class="text-lg font-bold text-blue-900 dark:text-blue-100">
                                        Rp {{ number_format($stockPriceData['close'], 0, ',', '.') }}
                                    </p>
                                </div>

                                <div class="{{ $stockPriceData['change'] >= 0 ? 'bg-green-50 dark:bg-green-950/20 border-green-200 dark:border-green-800' : 'bg-red-50 dark:bg-red-950/20 border-red-200 dark:border-red-800' }} rounded-lg p-3 border">
                                    <p class="text-xs {{ $stockPriceData['change'] >= 0 ? 'text-green-600 dark:text-green-400' : 'text-red-600 dark:text-red-400' }} uppercase tracking-wider font-medium">Change</p>
                                    <p class="text-lg font-bold {{ $stockPriceData['change'] >= 0 ? 'text-green-700 dark:text-green-300' : 'text-red-700 dark:text-red-300' }}">
                                        {{ $stockPriceData['change'] >= 0 ? '+' : '' }}{{ number_format($stockPriceData['change'], 0, ',', '.') }}
                                        ({{ number_format($stockPriceData['change_pct'], 2, ',', '.') }}%)
                                    </p>
                                </div>

                                <div class="bg-emerald-50 dark:bg-emerald-950/20 border border-emerald-200 dark:border-emerald-800 rounded-lg p-3">
                                    <p class="text-xs text-emerald-600 dark:text-emerald-400 uppercase tracking-wider font-medium">High</p>
                                    <p class="text-sm font-medium text-emerald-900 dark:text-emerald-100">
                                        Rp {{ number_format($stockPriceData['high'], 0, ',', '.') }}
                                    </p>
                                </div>

                                <div class="bg-orange-50 dark:bg-orange-950/20 border border-orange-200 dark:border-orange-800 rounded-lg p-3">
                                    <p class="text-xs text-orange-600 dark:text-orange-400 uppercase tracking-wider font-medium">Low</p>
                                    <p class="text-sm font-medium text-orange-900 dark:text-orange-100">
                                        Rp {{ number_format($stockPriceData['low'], 0, ',', '.') }}
                                    </p>
                                </div>
                            </div>

                            <!-- Additional Info -->
                            <div class="pt-4 border-t border-gray-100 dark:border-zinc-700">
                                <div class="grid grid-cols-2 gap-4 text-sm">
                                    <div>
                                        <span class="text-gray-500 dark:text-zinc-400">Volume:</span>
                                        <span class="ml-2 font-medium text-gray-900 dark:text-white">
                                            {{ number_format($stockPriceData['volume'], 0, ',', '.') }}
                                        </span>
                                    </div>
                                    <div>
                                        <span class="text-gray-500 dark:text-zinc-400">Tanggal:</span>
                                        <span class="ml-2 font-medium text-gray-900 dark:text-white">
                                            {{ \Carbon\Carbon::parse($stockPriceData['date'])->format('d/m/Y') }}
                                        </span>
                                    </div>
                                </div>
                            </div>

                            <!-- Last Updated -->
                            <div class="text-xs text-gray-500 dark:text-zinc-400 text-center pt-2 border-t border-gray-100 dark:border-zinc-700">
                                Data terakhir: {{ now()->setTimezone(auth()->user()->timezone ?? 'Asia/Jakarta')->format('d/m/Y H:i') }}
                            </div>
                        </div>
                    </div>
                </div>
            @endif

            <!-- Quick Actions -->
            <div class="bg-white dark:bg-zinc-800 rounded-lg border border-gray-200 dark:border-zinc-700 overflow-hidden">
                <div class="px-6 py-4 border-b border-gray-200 dark:border-zinc-700 bg-gray-50 dark:bg-zinc-800/50">
                    <h3 class="text-lg font-semibold text-gray-900 dark:text-white">Aksi Cepat</h3>
                </div>
                <div class="p-6">
                    <div class="space-y-3">
                        @if($signal->status !== 'published')
                            <flux:button variant="primary" color="green" wire:click="publish" class="w-full" icon="check-circle">
                                Publikasikan Sinyal
                            </flux:button>
                        @endif

                        @if($signal->status !== 'cancelled')
                            <flux:button variant="outline" color="yellow" wire:click="cancel" class="w-full" icon="x-circle">
                                Batalkan Sinyal
                            </flux:button>
                        @endif

                        <flux:button variant="primary" href="{{ route('admin.signals.edit', $signal) }}" wire:navigate class="w-full" icon="pencil-square">
                            Edit Sinyal
                        </flux:button>

                        @if(!$isAutoGenerated)
                            <flux:button variant="danger" wire:click="delete"
                                       wire:confirm="{{ __('Apakah Anda yakin ingin menghapus sinyal ini?') }}"
                                       class="w-full" icon="trash">
                                Hapus Sinyal
                            </flux:button>
                        @else
                            <div class="flex items-center gap-2 p-3 bg-gray-50 dark:bg-zinc-700 rounded-lg">
                                <svg class="size-4 text-blue-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                                </svg>
                                <span class="text-sm text-gray-600 dark:text-zinc-400">Sinyal otomatis tidak dapat dihapus</span>
                            </div>
                        @endif
                    </div>
                </div>
            </div>

            <!-- Company Info -->
            @if($signal->stockCompany)
                <div class="bg-white dark:bg-zinc-800 rounded-lg border border-gray-200 dark:border-zinc-700 overflow-hidden">
                    <div class="px-6 py-4 border-b border-gray-200 dark:border-zinc-700 bg-gray-50 dark:bg-zinc-800/50">
                        <h3 class="text-lg font-semibold text-gray-900 dark:text-white">Informasi Perusahaan</h3>
                    </div>
                    <div class="p-6">
                        <div class="space-y-4">
                            <div class="flex justify-between items-center py-2 border-b border-gray-100 dark:border-zinc-700">
                                <span class="text-sm font-medium text-gray-500 dark:text-zinc-400">Nama Perusahaan:</span>
                                <span class="text-sm text-gray-900 dark:text-white">{{ $signal->stockCompany->nama_emiten ?? '-' }}</span>
                            </div>

                            <div class="flex justify-between items-center py-2 border-b border-gray-100 dark:border-zinc-700">
                                <span class="text-sm font-medium text-gray-500 dark:text-zinc-400">Sektor:</span>
                                <span class="text-sm text-gray-900 dark:text-white">{{ $signal->stockCompany->sektor ?? '-' }}</span>
                            </div>

                            <div class="flex justify-between items-center py-2 border-b border-gray-100 dark:border-zinc-700">
                                <span class="text-sm font-medium text-gray-500 dark:text-zinc-400">Sub Sektor:</span>
                                <span class="text-sm text-gray-900 dark:text-white">{{ $signal->stockCompany->sub_sektor ?? '-' }}</span>
                            </div>

                            @if($signal->stockCompany->website)
                                <div class="flex justify-between items-center py-2">
                                    <span class="text-sm font-medium text-gray-500 dark:text-zinc-400">Website:</span>
                                    <a href="{{ $signal->stockCompany->website }}" target="_blank" class="text-sm text-blue-600 dark:text-blue-400 hover:underline">
                                        {{ $signal->stockCompany->website }}
                                    </a>
                                </div>
                            @endif
                        </div>
                    </div>
                </div>
            @endif

            <!-- Signal History -->
            <div class="bg-white dark:bg-zinc-800 rounded-lg border border-gray-200 dark:border-zinc-700 overflow-hidden">
                <div class="px-6 py-4 border-b border-gray-200 dark:border-zinc-700 bg-gray-50 dark:bg-zinc-800/50">
                    <h3 class="text-lg font-semibold text-gray-900 dark:text-white">Riwayat Status</h3>
                </div>
                <div class="p-6">
                    <div class="space-y-4">
                        <!-- Created -->
                        <div class="flex items-start gap-3">
                            <div class="shrink-0 w-8 h-8 bg-gray-100 dark:bg-zinc-700 rounded-full flex items-center justify-center">
                                <svg class="size-4 text-gray-600 dark:text-zinc-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path>
                                </svg>
                            </div>
                            <div class="flex-1 min-w-0">
                                <p class="text-sm font-medium text-gray-900 dark:text-white">Dibuat</p>
                                <p class="text-sm text-gray-500 dark:text-zinc-400">{{ $signal->created_at->format('d/m/Y H:i') }}</p>
                            </div>
                        </div>

                        @if($signal->published_at)
                            <!-- Published -->
                            <div class="flex items-start gap-3">
                                <div class="shrink-0 w-8 h-8 bg-green-100 dark:bg-green-900/30 rounded-full flex items-center justify-center">
                                    <svg class="size-4 text-green-600 dark:text-green-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                                    </svg>
                                </div>
                                <div class="flex-1 min-w-0">
                                    <p class="text-sm font-medium text-gray-900 dark:text-white">Dipublikasikan</p>
                                    <p class="text-sm text-gray-500 dark:text-zinc-400">{{ $signal->published_at->format('d/m/Y H:i') }}</p>
                                </div>
                            </div>
                        @endif

                        <!-- Current Status -->
                        <div class="flex items-start gap-3">
                            <div class="shrink-0 w-8 h-8 bg-blue-100 dark:bg-blue-900/30 rounded-full flex items-center justify-center">
                                <svg class="size-4 text-blue-600 dark:text-blue-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                                </svg>
                            </div>
                            <div class="flex-1 min-w-0">
                                <p class="text-sm font-medium text-gray-900 dark:text-white">Status Saat Ini</p>
                                <div class="flex items-center gap-2 mt-1">
                                    <flux:badge color="{{ $signal->status === 'published' ? 'green' : ($signal->status === 'active' ? 'blue' : 'gray') }}" size="sm">
                                        {{ $signal->status_label }}
                                    </flux:badge>
                                </div>
                                <p class="text-sm text-gray-500 dark:text-zinc-400 mt-1">{{ $signal->updated_at->format('d/m/Y H:i') }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
