<div>
    <div class="relative mb-6 w-full">
        <flux:heading size="xl" level="1">
            Edit Sinyal Saham
            @if($isAutoGenerated)
                <flux:badge color="blue" size="sm" class="ml-3">
                    <svg class="size-3 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17h14a2 2 0 002-2V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"></path>
                    </svg>
                    Auto-generated
                </flux:badge>
            @endif
        </flux:heading>
        <flux:subheading size="lg" class="mb-6">
            {{ $signal->kode_emiten }} - {{ $signal->stockCompany->nama_emiten ?? 'Unknown Company' }}
        </flux:subheading>
        <flux:separator variant="subtle" />
    </div>

    <!-- Actions Bar -->
    <flux:button variant="ghost" size="sm" class="mb-3" href="{{ route('admin.signals.index') }}" wire:navigate icon="arrow-left">
        Kembali
    </flux:button>

    <!-- Alert Messages -->
    @session('error')
        <x-alert type="error" class="mb-4">{{ $value }}</x-alert>
    @endsession

    <!-- Edit Form -->
    <div class="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <!-- Main Form -->
        <div class="lg:col-span-2">
            <div class="bg-white dark:bg-zinc-800 rounded-lg border border-gray-200 dark:border-zinc-700 overflow-hidden">
                <div class="px-6 py-4 border-b border-gray-200 dark:border-zinc-700 bg-gray-50 dark:bg-zinc-800/50">
                    <h3 class="text-lg font-semibold text-gray-900 dark:text-white">Informasi Sinyal</h3>
                </div>
                <div class="p-6">
                    <form wire:submit.prevent="save" class="space-y-6">
                        @if($isAutoGenerated)
                            <!-- Auto-generated signal notice -->
                            <div class="bg-amber-50 dark:bg-amber-950/20 border border-amber-200 dark:border-amber-800 rounded-lg p-4">
                                <div class="flex items-start gap-3">
                                    <svg class="size-5 text-amber-600 dark:text-amber-400 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L3.732 16.5c-.77.833.192 2.5 1.732 2.5z"></path>
                                    </svg>
                                    <div>
                                        <h4 class="text-sm font-medium text-amber-900 dark:text-amber-100">Perhatian</h4>
                                        <p class="text-sm text-amber-700 dark:text-amber-300 mt-1">
                                            Sinyal ini dihasilkan otomatis oleh sistem. Data teknikal tidak dapat diubah, hanya status dan rekomendasi yang dapat dimodifikasi.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        @endif

                        <!-- Signal Type & Kode Emiten -->
                        <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                            <flux:select wire:model="signal_type" label="Tipe Sinyal" :disabled="$isAutoGenerated">
                                <flux:select.option value="manual">Manual</flux:select.option>
                                <flux:select.option value="technical">Technical</flux:select.option>
                                <flux:select.option value="fundamental">Fundamental</flux:select.option>
                                <flux:select.option value="momentum">Momentum</flux:select.option>
                                <flux:select.option value="value_breakthrough">Value Breakthrough</flux:select.option>
                            </flux:select>

                            <flux:input
                                wire:model.live="kode_emiten"
                                label="Kode Emiten"
                                placeholder="Contoh: BBCA"
                                :disabled="$isAutoGenerated"
                            />
                        </div>

                        <!-- Financial Ratios -->
                        <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
                            <flux:input
                                wire:model="market_cap"
                                label="Market Cap"
                                placeholder="1000000000000"
                                :disabled="$isAutoGenerated"
                            />

                            <flux:input
                                wire:model="pbv"
                                label="PBV"
                                placeholder="1.25"
                                :disabled="$isAutoGenerated"
                            />

                            <flux:input
                                wire:model="per"
                                label="PER"
                                placeholder="15.5"
                                :disabled="$isAutoGenerated"
                            />
                        </div>

                        <div class="grid grid-cols-1 md:grid-cols-3 gap-6 mb-6">
                            <!-- Before Data (H-1) -->
                            <div class="bg-blue-50 dark:bg-blue-950/20 rounded-lg border border-blue-200 dark:border-blue-800 overflow-hidden">
                                <div class="px-4 py-3 border-b border-blue-200 dark:border-blue-800 bg-blue-100 dark:bg-blue-900/30">
                                    <div class="flex items-center gap-2">
                                        <flux:icon.arrow-left class="size-4 text-blue-600 dark:text-blue-400" />
                                        <h4 class="text-sm font-semibold text-blue-900 dark:text-blue-100">Data Sebelum (H-1)</h4>
                                    </div>
                                </div>
                                <div class="p-4">
                                    <div class="grid grid-cols-2 md:grid-cols-1 gap-4">
                                        <flux:input
                                            wire:model="before_date"
                                            label="Tanggal"
                                            :disabled="$isAutoGenerated"
                                        />

                                        <flux:input
                                            wire:model="before_value"
                                            label="Nilai"
                                            :disabled="$isAutoGenerated"
                                        />

                                        <flux:input
                                            wire:model="before_close"
                                            label="Harga Close"
                                            :disabled="$isAutoGenerated"
                                        />

                                        <flux:input
                                            wire:model="before_volume"
                                            label="Volume"
                                            :disabled="$isAutoGenerated"
                                        />
                                    </div>
                                </div>
                            </div>

                            <!-- Hit Data (H) -->
                            <div class="bg-purple-50 dark:bg-purple-950/20 rounded-lg border border-purple-200 dark:border-purple-800 overflow-hidden">
                                <div class="px-4 py-3 border-b border-purple-200 dark:border-purple-800 bg-purple-100 dark:bg-purple-900/30">
                                    <div class="flex items-center gap-2">
                                        <svg class="size-4 text-purple-600 dark:text-purple-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"></path>
                                        </svg>
                                        <h4 class="text-sm font-semibold text-purple-900 dark:text-purple-100">Data Breakthrough (H)</h4>
                                    </div>
                                </div>
                                <div class="p-4">
                                    <div class="grid grid-cols-2 md:grid-cols-1 gap-4">
                                        <flux:input
                                            wire:model="hit_date"
                                            label="Tanggal Hit"
                                            :disabled="$isAutoGenerated"
                                        />

                                        <flux:input
                                            wire:model="hit_value"
                                            label="Nilai"
                                            :disabled="$isAutoGenerated"
                                        />

                                        <flux:input
                                            wire:model="hit_close"
                                            label="Harga Close"
                                            :disabled="$isAutoGenerated"
                                        />

                                        <flux:input
                                            wire:model="hit_volume"
                                            label="Volume"
                                            :disabled="$isAutoGenerated"
                                        />
                                    </div>
                                </div>
                            </div>

                            <!-- After Data (H+1) -->
                            <div class="bg-green-50 dark:bg-green-950/20 rounded-lg border border-green-200 dark:border-green-800 overflow-hidden">
                                <div class="px-4 py-3 border-b border-green-200 dark:border-green-800 bg-green-100 dark:bg-green-900/30">
                                    <div class="flex items-center gap-2">
                                        <flux:icon.arrow-right class="size-4 text-green-600 dark:text-green-400" />
                                        <h4 class="text-sm font-semibold text-green-900 dark:text-green-100">Data Sesudah (H+1)</h4>
                                    </div>
                                </div>
                                <div class="p-4">
                                    <div class="grid grid-cols-2 md:grid-cols-1 gap-4">
                                        <flux:input
                                            wire:model="after_date"
                                            label="Tanggal"
                                            :disabled="$isAutoGenerated"
                                        />

                                        <flux:input
                                            wire:model="after_value"
                                            label="Nilai"
                                            :disabled="$isAutoGenerated"
                                        />

                                        <flux:input
                                            wire:model="after_close"
                                            label="Harga Close"
                                            :disabled="$isAutoGenerated"
                                        />

                                        <flux:input
                                            wire:model="after_volume"
                                            label="Volume"
                                            :disabled="$isAutoGenerated"
                                        />
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- Recommendation -->
                        <div>
                            <flux:textarea
                                wire:model="recommendation"
                                label="Rekomendasi"
                                placeholder="Jelaskan rekomendasi investasi untuk saham ini..."
                                rows="4"
                            />
                            <p class="text-xs text-gray-500 dark:text-zinc-400 mt-2">Maksimal 2000 karakter</p>
                        </div>

                        <!-- Notes -->
                        <div>
                            <flux:textarea
                                wire:model="notes"
                                label="Catatan"
                                placeholder="Catatan tambahan tentang sinyal ini..."
                                rows="4"
                            />
                            <p class="text-xs text-gray-500 dark:text-zinc-400 mt-2">Maksimal 1000 karakter</p>
                        </div>

                        <!-- Status & Notes -->
                        <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                            <flux:select wire:model="status" label="Status">
                                <flux:select.option value="">Pilih Status</flux:select.option>
                                <flux:select.option value="draft">Draft</flux:select.option>
                                <flux:select.option value="active">Active</flux:select.option>
                                <flux:select.option value="published">Published</flux:select.option>
                                <flux:select.option value="expired">Expired</flux:select.option>
                                <flux:select.option value="cancelled">Cancelled</flux:select.option>
                            </flux:select>
                        </div>

                        <!-- Submit Buttons -->
                        <div class="flex items-center justify-end gap-4 pt-4 border-t border-gray-200 dark:border-zinc-700">
                            <flux:button variant="ghost" size="sm" icon="x-mark" href="{{ route('admin.signals.index') }}" wire:navigate>Batal</flux:button>
                            <flux:button type="submit" size="sm" icon="check" variant="primary" wire:loading.attr="disabled">Update</flux:button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <!-- Info Panel -->
        <div class="lg:col-span-1 space-y-6">
            <!-- Signal Information -->
            <div class="bg-white dark:bg-zinc-800 rounded-lg border border-gray-200 dark:border-zinc-700 overflow-hidden">
                <div class="px-6 py-4 border-b border-gray-200 dark:border-zinc-700 bg-gray-50 dark:bg-zinc-800/50">
                    <h3 class="text-lg font-semibold text-gray-900 dark:text-white">Informasi Sinyal</h3>
                </div>
                <div class="p-6">
                    <div class="space-y-4">
                        <div class="flex justify-between items-center py-2 border-b border-gray-100 dark:border-zinc-700">
                            <span class="text-sm font-medium text-gray-500 dark:text-zinc-400">Dibuat:</span>
                            <span class="text-sm text-gray-900 dark:text-white">{{ $signal->created_at->format('d/m/Y H:i') }}</span>
                        </div>

                        <div class="flex justify-between items-center py-2 border-b border-gray-100 dark:border-zinc-700">
                            <span class="text-sm font-medium text-gray-500 dark:text-zinc-400">Diubah:</span>
                            <span class="text-sm text-gray-900 dark:text-white">{{ $signal->updated_at->format('d/m/Y H:i') }}</span>
                        </div>

                        @if($signal->published_at)
                            <div class="flex justify-between items-center py-2 border-b border-gray-100 dark:border-zinc-700">
                                <span class="text-sm font-medium text-gray-500 dark:text-zinc-400">Dipublikasikan:</span>
                                <span class="text-sm text-gray-900 dark:text-white">{{ $signal->published_at->format('d/m/Y H:i') }}</span>
                            </div>
                        @endif

                        <div class="flex justify-between items-center py-2">
                            <span class="text-sm font-medium text-gray-500 dark:text-zinc-400">Oleh:</span>
                            <span class="text-sm text-gray-900 dark:text-white">
                                @if($signal->user)
                                    {{ $signal->user->name }}
                                @else
                                    <span class="text-gray-500 dark:text-zinc-400">Sistem</span>
                                @endif
                            </span>
                        </div>
                    </div>

                    @if($isAutoGenerated)
                        <div class="mt-6 pt-4 border-t border-gray-200 dark:border-zinc-700">
                            <div class="flex items-start gap-3 p-3 bg-blue-50 dark:bg-blue-950/20 rounded-lg">
                                <svg class="size-5 text-blue-600 dark:text-blue-400 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17h14a2 2 0 002-2V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"></path>
                                </svg>
                                <div>
                                    <h4 class="text-sm font-medium text-blue-900 dark:text-blue-100">Sinyal Otomatis</h4>
                                    <p class="text-sm text-blue-700 dark:text-blue-300 mt-1">
                                        Sinyal ini dihasilkan oleh command analisis otomatis. Data teknikal tidak dapat diubah untuk menjaga integritas data.
                                    </p>
                                </div>
                            </div>
                        </div>
                    @endif
                </div>
            </div>

            <!-- Edit Guide -->
            <div class="bg-white dark:bg-zinc-800 rounded-lg border border-gray-200 dark:border-zinc-700 overflow-hidden">
                <div class="px-6 py-4 border-b border-gray-200 dark:border-zinc-700 bg-gray-50 dark:bg-zinc-800/50">
                    <h3 class="text-lg font-semibold text-gray-900 dark:text-white">Panduan Edit</h3>
                </div>
                <div class="p-6">
                    <div class="space-y-4">
                        <div>
                            <h4 class="text-sm font-semibold text-gray-900 dark:text-white mb-2">Yang Bisa Diubah:</h4>
                            <ul class="text-sm text-gray-600 dark:text-zinc-400 space-y-1">
                                <li class="flex items-center gap-2">
                                    <svg class="size-4 text-green-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
                                    </svg>
                                    <strong>Status:</strong> Ubah status sinyal
                                </li>
                                <li class="flex items-center gap-2">
                                    <svg class="size-4 text-green-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
                                    </svg>
                                    <strong>Rekomendasi:</strong> Modifikasi teks rekomendasi
                                </li>
                                <li class="flex items-center gap-2">
                                    <svg class="size-4 text-green-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
                                    </svg>
                                    <strong>Catatan:</strong> Tambahkan catatan tambahan
                                </li>
                                @if(!$isAutoGenerated)
                                    <li class="flex items-center gap-2">
                                        <svg class="size-4 text-green-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
                                        </svg>
                                        <strong>Data Teknis:</strong> Semua data teknikal dapat diubah
                                    </li>
                                @endif
                            </ul>
                        </div>

                        @if($isAutoGenerated)
                            <div class="pt-4 border-t border-gray-200 dark:border-zinc-700">
                                <h4 class="text-sm font-semibold text-gray-900 dark:text-white mb-2">Yang Tidak Bisa Diubah:</h4>
                                <ul class="text-sm text-gray-500 dark:text-zinc-500 space-y-1">
                                    <li class="flex items-center gap-2">
                                        <svg class="size-4 text-red-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
                                        </svg>
                                        Data teknikal (harga, volume, dll)
                                    </li>
                                    <li class="flex items-center gap-2">
                                        <svg class="size-4 text-red-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
                                        </svg>
                                        Tanggal breakthrough
                                    </li>
                                    <li class="flex items-center gap-2">
                                        <svg class="size-4 text-red-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
                                        </svg>
                                        Rasio fundamental
                                    </li>
                                </ul>
                            </div>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
