<?php

namespace App\Livewire\Signals\Admin;

use Livewire\Component;
use App\Models\StockSignal;

class SignalsEdit extends Component
{
    public StockSignal $signal;

    public $signal_type;
    public $kode_emiten;
    public $market_cap;
    public $pbv;
    public $per;
    public $hit_date;
    public $hit_value;
    public $hit_close;
    public $hit_volume;
    public $before_date;
    public $before_value;
    public $before_close;
    public $before_volume;
    public $after_date;
    public $after_value;
    public $after_close;
    public $after_volume;
    public $status;
    public $notes;
    public $recommendation;

    public $isAutoGenerated = false;

    protected function rules()
    {
        $baseRules = [
            'status' => 'required|in:draft,active,published,cancelled,expired',
            'notes' => 'nullable|string|max:1000',
            'recommendation' => 'required|string|max:2000',
        ];

        // Only allow editing signal data if it's not auto-generated
        if (!$this->isAutoGenerated) {
            $baseRules = array_merge($baseRules, [
                'signal_type' => 'required|string',
                'kode_emiten' => 'required|string|max:10',
                'market_cap' => 'nullable|numeric|min:0',
                'pbv' => 'nullable|numeric|min:0',
                'per' => 'nullable|numeric|min:0',
                'hit_date' => 'required|date',
                'hit_value' => 'required|numeric|min:0',
                'hit_close' => 'required|numeric|min:0',
                'hit_volume' => 'required|integer|min:0',
                'before_date' => 'nullable|date',
                'before_value' => 'nullable|numeric|min:0',
                'before_close' => 'nullable|numeric|min:0',
                'before_volume' => 'nullable|integer|min:0',
                'after_date' => 'nullable|date',
                'after_value' => 'nullable|numeric|min:0',
                'after_close' => 'nullable|numeric|min:0',
                'after_volume' => 'nullable|integer|min:0',
            ]);
        }

        return $baseRules;
    }

    protected $validationAttributes = [
        'kode_emiten' => 'Kode Emiten',
        'market_cap' => 'Market Cap',
        'pbv' => 'PBV',
        'per' => 'PER',
        'hit_date' => 'Tanggal Hit',
        'hit_value' => 'Nilai Hit',
        'hit_close' => 'Harga Close Hit',
        'hit_volume' => 'Volume Hit',
        'before_date' => 'Tanggal Sebelum',
        'before_value' => 'Nilai Sebelum',
        'before_close' => 'Harga Close Sebelum',
        'before_volume' => 'Volume Sebelum',
        'after_date' => 'Tanggal Sesudah',
        'after_value' => 'Nilai Sesudah',
        'after_close' => 'Harga Close Sesudah',
        'after_volume' => 'Volume Sesudah',
        'status' => 'Status',
        'notes' => 'Catatan',
        'recommendation' => 'Rekomendasi',
    ];

    public function mount(StockSignal $signal)
    {
        $this->signal = $signal;

        // Check if this is an auto-generated signal
        $this->isAutoGenerated = $signal->signal_type === 'value_breakthrough' && is_null($signal->user_id);

        // Populate form data
        $this->signal_type = $signal->signal_type;
        $this->kode_emiten = $signal->kode_emiten;
        $this->market_cap = $signal->market_cap ? number_format($signal->market_cap, 0, ',', '.') : null;
        $this->pbv = $signal->pbv ? number_format($signal->pbv, 2, ',', '.') : null;
        $this->per = $signal->per ? number_format($signal->per, 2, ',', '.') : null;
        $this->hit_date = $signal->hit_date?->format('d-m-Y');
        $this->hit_value = $signal->hit_value ? number_format($signal->hit_value, 0, ',', '.') : null;
        $this->hit_close = $signal->hit_close ? number_format($signal->hit_close, 0, ',', '.') : null;
        $this->hit_volume = $signal->hit_volume ? number_format($signal->hit_volume, 0, ',', '.') : null;
        $this->before_date = $signal->before_date?->format('d-m-Y');
        $this->before_value = $signal->before_value ? number_format($signal->before_value, 0, ',', '.') : null;
        $this->before_close = $signal->before_close ? number_format($signal->before_close, 0, ',', '.') : null;
        $this->before_volume = $signal->before_volume ? number_format($signal->before_volume, 0, ',', '.') : null;
        $this->after_date = $signal->after_date?->format('d-m-Y');
        $this->after_value = $signal->after_value ? number_format($signal->after_value, 0, ',', '.') : null;
        $this->after_close = $signal->after_close ? number_format($signal->after_close, 0, ',', '.') : null;
        $this->after_volume = $signal->after_volume ? number_format($signal->after_volume, 0, ',', '.') : null;
        $this->status = $signal->status;
        $this->notes = $signal->notes;
        $this->recommendation = $signal->recommendation;
    }

    public function updatedKodeEmiten()
    {
        if (!$this->isAutoGenerated) {
            $this->kode_emiten = strtoupper($this->kode_emiten);
        }
    }

    public function save()
    {
        $this->validate();

        try {
            $updateData = [
                'status' => $this->status,
                'notes' => $this->notes ?: null,
                'recommendation' => $this->recommendation,
            ];

            // Set published_at based on status
            if ($this->status === 'published') {
                $updateData['published_at'] = now();
            } elseif ($this->signal->status === 'published' && $this->status !== 'published') {
                $updateData['published_at'] = null;
            }

            // Only update signal data if it's not auto-generated
            if (!$this->isAutoGenerated) {
                $updateData = array_merge($updateData, [
                    'signal_type' => $this->signal_type,
                    'kode_emiten' => strtoupper($this->kode_emiten),
                    'market_cap' => $this->market_cap ?: null,
                    'pbv' => $this->pbv ?: null,
                    'per' => $this->per ?: null,
                    'hit_date' => $this->hit_date,
                    'hit_value' => $this->hit_value,
                    'hit_close' => $this->hit_close,
                    'hit_volume' => $this->hit_volume,
                    'before_date' => $this->before_date ?: null,
                    'before_value' => $this->before_value ?: null,
                    'before_close' => $this->before_close ?: null,
                    'before_volume' => $this->before_volume ?: null,
                    'after_date' => $this->after_date ?: null,
                    'after_value' => $this->after_value ?: null,
                    'after_close' => $this->after_close ?: null,
                    'after_volume' => $this->after_volume ?: null,
                ]);
            }

            $this->signal->update($updateData);

            session()->flash('success', 'Sinyal berhasil diperbarui.');

            return $this->redirect('/admin/signals', true);

        } catch (\Exception $e) {
            session()->flash('error', 'Terjadi kesalahan: ' . $e->getMessage());
        }
    }

    public function render()
    {
        return view('livewire.signals.admin.signals-edit');
    }
}
