<?php

namespace App\Livewire\Signals\Admin;

use Livewire\Component;
use App\Models\StockSignal;
use App\Models\TradingInfo;
use App\Models\StockCompany;
use App\Models\FinancialRatio;

class SignalsEdit extends Component
{
    public StockSignal $signal;

    public $signal_type;
    public $kode_emiten;
    public $market_cap;
    public $pbv;
    public $per;
    public $hit_date;
    public $hit_value;
    public $hit_close;
    public $hit_volume;
    public $before_date;
    public $before_value;
    public $before_close;
    public $before_volume;
    public $after_date;
    public $after_value;
    public $after_close;
    public $after_volume;
    public $status;
    public $notes;
    public $recommendation;

    public $isAutoGenerated = false;
    public $companyFound = true;

    protected function rules()
    {
        $baseRules = [
            'status' => 'required|in:draft,active,published,cancelled,expired',
            'notes' => 'nullable|string|max:1000',
            'recommendation' => 'required|string|max:2000',
        ];

        // Only allow editing signal data if it's not auto-generated
        if (!$this->isAutoGenerated) {
            $baseRules = array_merge($baseRules, [
                'signal_type' => 'required|string',
                'kode_emiten' => 'required|string|max:10|exists:stock_companies,kode_emiten',
            ]);
        }

        return $baseRules;
    }

    protected $validationAttributes = [
        'kode_emiten' => 'Kode Emiten',
        'status' => 'Status',
        'notes' => 'Catatan',
        'recommendation' => 'Rekomendasi',
    ];

    protected function messages()
    {
        return [
            'kode_emiten.exists' => 'Kode Emiten tidak ditemukan dalam database perusahaan saham.',
        ];
    }

    public function updatedKodeEmiten()
    {
        if (!$this->isAutoGenerated) {
            $this->kode_emiten = strtoupper($this->kode_emiten);
        }

        // Check if company exists
        if ($this->kode_emiten) {
            $company = StockCompany::where('kode_emiten', $this->kode_emiten)->first();
            $this->companyFound = $company !== null;
        } else {
            $this->companyFound = false;
        }
    }

    public function mount(StockSignal $signal)
    {
        $this->signal = $signal;

        // Check if this is an auto-generated signal
        $this->isAutoGenerated = $signal->signal_type === 'value_breakthrough' && is_null($signal->user_id);

        // Populate form data
        $this->signal_type = $signal->signal_type;
        $this->kode_emiten = $signal->kode_emiten;
        $this->market_cap = $signal->market_cap ? number_format($signal->market_cap, 0, ',', '.') : null;
        $this->pbv = $signal->pbv ? number_format($signal->pbv, 2, ',', '.') : null;
        $this->per = $signal->per ? number_format($signal->per, 2, ',', '.') : null;
        $this->hit_date = $signal->hit_date?->format('d-m-Y');
        $this->hit_value = $signal->hit_value ? number_format($signal->hit_value, 0, ',', '.') : null;
        $this->hit_close = $signal->hit_close ? number_format($signal->hit_close, 0, ',', '.') : null;
        $this->hit_volume = $signal->hit_volume ? number_format($signal->hit_volume, 0, ',', '.') : null;
        $this->before_date = $signal->before_date?->format('d-m-Y');
        $this->before_value = $signal->before_value ? number_format($signal->before_value, 0, ',', '.') : null;
        $this->before_close = $signal->before_close ? number_format($signal->before_close, 0, ',', '.') : null;
        $this->before_volume = $signal->before_volume ? number_format($signal->before_volume, 0, ',', '.') : null;
        $this->after_date = $signal->after_date?->format('d-m-Y');
        $this->after_value = $signal->after_value ? number_format($signal->after_value, 0, ',', '.') : null;
        $this->after_close = $signal->after_close ? number_format($signal->after_close, 0, ',', '.') : null;
        $this->after_volume = $signal->after_volume ? number_format($signal->after_volume, 0, ',', '.') : null;
        $this->status = $signal->status;
        $this->notes = $signal->notes;
        $this->recommendation = $signal->recommendation;
    }

    public function save()
    {
        $this->validate();

        try {
            $updateData = [
                'status' => $this->status,
                'notes' => $this->notes ?: null,
                'recommendation' => $this->recommendation,
            ];

            // Set published_at based on status
            if ($this->status === 'published') {
                $updateData['published_at'] = now();
            } elseif ($this->signal->status === 'published' && $this->status !== 'published') {
                $updateData['published_at'] = null;
            }

            // Get market cap for the company
            $marketCap = TradingInfo::where('kode_emiten', $this->kode_emiten)->latest('date')->first();
            if ($marketCap) {
                $updateData['market_cap'] = $marketCap->close * $marketCap->listed_shares;
            }

            // Get financial ratios for the company
            $financialRatios = FinancialRatio::where('code', $this->kode_emiten)->latest('fs_date')->first();
            if ($financialRatios) {
                $updateData['pbv'] = $financialRatios->price_bv;
                $updateData['per'] = $financialRatios->per;
            }


            // Only update signal data if it's not auto-generated
            if (!$this->isAutoGenerated) {
                $updateData = array_merge($updateData, [
                    'signal_type' => $this->signal_type,
                    'kode_emiten' => strtoupper($this->kode_emiten),
                ]);
            }

            $this->signal->update($updateData);

            session()->flash('success', 'Sinyal berhasil diperbarui.');

            return $this->redirect('/admin/signals', true);

        } catch (\Exception $e) {
            session()->flash('error', 'Terjadi kesalahan: ' . $e->getMessage());
        }
    }

    public function render()
    {
        return view('livewire.signals.admin.signals-edit');
    }
}
