<?php

namespace App\Livewire\Signals\Admin;

use App\Models\StockSignal;
use Livewire\Component;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;

class SignalsShow extends Component
{
    public StockSignal $signal;
    public $isAutoGenerated = false;
    public $stockPriceData = null;

    public function mount(StockSignal $signal)
    {
        $this->signal = $signal;
        $this->isAutoGenerated = $signal->signal_type === 'value_breakthrough' && is_null($signal->user_id);

        // Fetch stock price data
        $this->fetchStockPrice();
    }

    public function publish()
    {
        $this->signal->publish();
        session()->flash('success', 'Sinyal berhasil dipublikasikan.');
        $this->signal->refresh();
    }

    public function cancel()
    {
        $this->signal->cancel();
        session()->flash('success', 'Sinyal berhasil dibatalkan.');
        $this->signal->refresh();
    }

    public function delete()
    {
        // Check if signal is auto-generated
        if ($this->isAutoGenerated) {
            session()->flash('error', 'Sinyal yang dihasilkan otomatis tidak dapat dihapus.');
            return;
        }

        $this->signal->delete();
        session()->flash('success', 'Sinyal berhasil dihapus.');
        return $this->redirect('/admin/signals', true);
    }

    public function selectStock($kodeEmiten)
    {
        // Update default_kode_emiten for current user
        auth()->user()->update(['default_kode_emiten' => $kodeEmiten]);

        // Redirect to dashboard
        return $this->redirect('/dashboard', true);
    }

    private function fetchStockPrice()
    {
        try {
            $baseUrl = env('GOAPI_BASE_URL');
            $apiKey = env('GOAPI_KEY');

            if (!$apiKey) {
                return;
            }

            $response = Http::withHeaders([
                'accept' => 'application/json',
                'X-API-KEY' => $apiKey,
            ])->get("{$baseUrl}/stock/idx/prices", [
                'symbols' => $this->signal->kode_emiten,
            ]);

            if ($response->ok()) {
                $data = $response->json();
                if (isset($data['status']) && $data['status'] === 'success' && !empty($data['data']['results'])) {
                    $this->stockPriceData = $data['data']['results'][0];
                }
            }
        } catch (\Exception $e) {
            // Silently fail if API is not available
            Log::warning('Failed to fetch stock price: ' . $e->getMessage());
        }
    }

    public function render()
    {
        return view('livewire.signals.admin.signals-show');
    }
}
